# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Supertonic3 TTS
version: "1.2.0"
slug: supertonic_tts
description: Ultra-fast, on-device text-to-speech powered by Supertonic3 with multilingual support
url: "https://github.com/jijamik/HA-Supertonic-Addon"
arch:
  - aarch64
  - amd64
  - armv7
init: false
startup: services
boot: auto
hassio_api: true
hassio_role: default
host_network: true
discovery:
  - wyoming
backup_exclude:
  - "*.onnx"
map:
  - share:rw
options:
  default_language: "fr"
  default_voice: "M4"
  speed: 1.5
  volume_boost: 2.0
  quality: 5
  debug_logging: false
schema:
  default_language: "list(en|ko|ja|ar|bg|cs|da|de|el|es|et|fi|fr|hi|hr|hu|id|it|lt|lv|nl|pl|pt|ro|ru|sk|sl|sv|tr|uk|vi|na)"
  default_voice: "list(M1|M2|M3|M4|M5|F1|F2|F3|F4|F5)"
  speed: "float(0.7,2.0)"
  volume_boost: "float(1.0,3.0)"
  quality: "int(2,15)"
  debug_logging: "bool"
